

#20170714 添加logstash-filter-ruby
# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash:5.4.3

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
# 官网已经默认安装了ruby
#RUN logstash-plugin install logstash-filter-ruby
